name: ThornyaMain
author: Gusttavo13
description: A Template
main: club.thornya.thornyarpg.ThornyaMain
website: https://github.com/Thornya-Club/ThornyaMain
version: ${project.version}
api-version: 1.17